# @package _global_
model:
  _name_: lightconv
  d_model: 768
  d_inner: ${eval:'${model.d_model} * 4'}
  n_encoding_layer: 7
  n_decoding_layer: ${model.n_layer}
  n_heads: ${eval:'${model.d_model} / 32'}
  n_kv_heads: ${model.n_heads}
  max_seq_len: 256
  conv_type: lightweight
  weight_softmax: True
  n_layer: 6
  decoder_only: True
